version: "3.8"
services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - data:/data/db

  backend:
    build: ./backend
    container_name: solisalim-api
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      PORT: 5000
      MONGODB_URL: mongodb://mongodb:27017/solisalim
      JWT_SECRET: SECRET
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: solisalim-web
    ports:
      - "3001:80"

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8080:80"
    links:
      - frontend
      - backend

volumes:
  data:
